name: go-test
on:
  push:
    branches:
      - 'main'
  pull_request:

permissions:
  contents: read

jobs:
  go-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Set up Go
        uses: actions/setup-go@v6.5.0
        with:
          go-version-file: .go-version
      - name: Set up XenServer Go SDK
        uses: ./.github/actions/setup-xenserver-sdk
        with:
          sdk-url: ${{ vars.XENSERVER_SDK_URL }}
      # UT requires a live XenServer host (un-mocked XenAPI), so skip in CI
      - name: Build
        run: go build ./...
