# Manual release workflow is used for deploying documentation updates
# on the specified branch without making an official plugin release. 
name: Notify Integration Release (Manual)
on:
  workflow_dispatch:
    inputs:
      version:
        description: "The release version (semver)"
        default: 1.0.0
        required: false
      branch:
        description: "A branch or SHA"
        default: 'main'
        required: false
jobs:
  notify-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v7.0.0
        with:
          ref: ${{ github.event.inputs.branch }}
      # Ensure that Docs are Compiled
      - uses: actions/setup-go@v6.5.0
        with:
          go-version-file: .go-version
          cache: false
      - name: Set up XenServer Go SDK
        uses: ./.github/actions/setup-xenserver-sdk
        with:
          sdk-url: ${{ vars.XENSERVER_SDK_URL }}
      - shell: bash
        run: make generate
      - shell: bash
        run: |
          if [[ -z "$(git status -s)" ]]; then
            echo "OK"
          else
            echo "Docs have been updated, but the compiled docs have not been committed."
            echo "Run 'make generate', and commit the result to resolve this error."
            exit 1
          fi
      # Perform the Release
      - name: Checkout integration-release-action
        uses: actions/checkout@v7.0.0
        with:
          repository: hashicorp/integration-release-action
          path: ./integration-release-action
      - name: Notify Release
        uses: ./integration-release-action
        with:
          integration_identifier: "packer/xenserver/xenserver"
          release_version: ${{ github.event.inputs.version }}
          release_sha: ${{ github.event.inputs.branch }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
